spring:
  mvc:
    view: {prefix: /WEB-INF/jsp/ , suffix: .jsp}
  main:
    banner-mode: off #console icon
  profiles:
    active: dev,prod #logback-spring.xml
  datasource:
    url: jdbc:mysql://localhost:3306/day1?serverTimezone=UTC&useSSL=false
    username: root
    password: 12345678
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

# Value Config
demo:
  id: 0
  name: max
  food:
    meat: pizza
    dessert: cake
  hobby: [netflix,music]
  drink:
    - coffee
    - tea
  obj2:
    - code: 407
      city: 台中
      have-fun: true
    - code: 616
      city: 嘉義
      have-fun: false

basic:
  username_1: "john"
  password_2: "321"

#server:
#  port: 8080
#  servlet:
#    context-path: /note
